# Generated by Django 2.2.3 on 2019-07-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0003_auto_20190730_1124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackingdata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trackingdata',
            name='song',
        ),
        migrations.RemoveField(
            model_name='trackingdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='TrackingData',
        ),
    ]
